---
  - name: "configure-server" 
    hosts: web
    user: ubuntu
    become: true
    become_method: sudo
    become_user: root  
    gather_facts: false
    vars:
      - ansible_python_interpreter: /usr/bin/python3
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml
      - NODEJS_VERSION: 14.x   

    pre_tasks:
      - name: "Install python 2"
        ansible.builtin.apt:
          name: 'python2'
          state: present
          update_cache: yes

    roles:
      - configure-server