version: 2.1
executors:
  node:
    docker:
      - image: node:14-alpine
jobs:
  build_frontend:
    executor: node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Compile code check
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths:
            - frontend/node_modules
          key: fe-cached-{{ checksum "frontend/package-lock.json" }}
  build_backend:
    executor: node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Compile code check
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths:
            - backend/node_modules
          key: be-cached-{{ checksum "backend/package-lock.json" }}

workflows:
  ci-pipeline:
    jobs:
      - build_frontend
      - build_backend
