version: 2.1
executors:
  node:
    docker:
      - image: node:14-alpine
jobs:
  build_frontend:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: fe-cache-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Compile code
          command: npm run build
  build_backend:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: be-cache-{{ checksum "backend/package-lock.json" }}
      - run:
          name: Compile code
          command: npm run build

workflows:
  ci-pipeline:
    jobs:
      - build_frontend
